[[redirects]]
  from = "/daftar"
  to = "/pilih-minat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/daftar"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/masuk"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/artikel"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/pertanyaan"
  status = 301
  force = true